package games.ballGame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.Timer;

public class BallGame extends javax.swing.JFrame {

    /**
     * Creates new form BallGame
     */
    public BallGame() {
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBall = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        lblPoints = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ball Game");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        btnBall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Player/coin.png"))); // NOI18N
        btnBall.setBorderPainted(false);
        btnBall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBallActionPerformed(evt);
            }
        });
        getContentPane().add(btnBall);
        btnBall.setBounds(0, 0, 40, 40);

        lblScore.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lblScore.setForeground(new java.awt.Color(255, 255, 255));
        lblScore.setText("Puntaje: ");
        getContentPane().add(lblScore);
        lblScore.setBounds(0, 260, 120, 40);

        lblPoints.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lblPoints.setForeground(new java.awt.Color(255, 255, 255));
        lblPoints.setText("0");
        getContentPane().add(lblPoints);
        lblPoints.setBounds(120, 260, 60, 40);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        Timer timer = new Timer(800, new ActionListener() {
            
        @Override
        public void actionPerformed(ActionEvent e) {

            Random random = new Random();
            int x = random.nextInt((350 - 0 + 1)) + 0;
            int y = random.nextInt((180 - 0 + 1)) + 0;
            btnBall.setLocation(x, y);

        }                       
            
        });
        
        timer.start();
                
    }//GEN-LAST:event_formWindowOpened

    private void btnBallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBallActionPerformed
        
        int z = Integer.parseInt(lblPoints.getText());
        lblPoints.setText("" + (z + 100));
        
        if (z == 400) {
            
            lblPoints.setVisible(false);
            lblScore.setVisible(false);
            btnBall.setVisible(false);
            jLabel1.setText("Ganaste");
            
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnBallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BallGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BallGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BallGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BallGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BallGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPoints;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables
}
