package games.TicTacToe.game;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class TicTacToe extends javax.swing.JFrame {

    String turn = "X";
    String nextGame = "O";
    JLabel boxes[] = new JLabel[9];
    int victories[][] = {{1,2,3}, {4,5,6}, {7,8,9}, {1,4,7}, {2,5,8}, {3,6,9}, {1,5,9}, {3,5,7}};
    boolean available = true;
        
    public TicTacToe() {
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        lblWinner.setVisible(false);
        
        boxes[0] = box1;
        boxes[1] = box2;
        boxes[2] = box3;
        boxes[3] = box4;
        boxes[4] = box5;
        boxes[5] = box6;
        boxes[6] = box7;
        boxes[7] = box8;
        boxes[8] = box9;                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        box1 = new javax.swing.JLabel();
        box2 = new javax.swing.JLabel();
        box3 = new javax.swing.JLabel();
        box4 = new javax.swing.JLabel();
        box5 = new javax.swing.JLabel();
        box6 = new javax.swing.JLabel();
        box7 = new javax.swing.JLabel();
        box8 = new javax.swing.JLabel();
        box9 = new javax.swing.JLabel();
        btnNextGame = new javax.swing.JButton();
        btnInstructions = new javax.swing.JButton();
        lblTurn = new javax.swing.JLabel();
        lblScoreX = new javax.swing.JLabel();
        lblPointsX = new javax.swing.JLabel();
        lblScoreO = new javax.swing.JLabel();
        lblPointsO = new javax.swing.JLabel();
        lblWinner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(353, 605));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        box1.setBackground(new java.awt.Color(255, 255, 255));
        box1.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        box1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box1.setOpaque(true);
        box1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box1MousePressed(evt);
            }
        });

        box2.setBackground(new java.awt.Color(255, 255, 255));
        box2.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        box2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box2.setOpaque(true);
        box2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box2MousePressed(evt);
            }
        });

        box3.setBackground(new java.awt.Color(255, 255, 255));
        box3.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        box3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box3.setOpaque(true);
        box3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box3MousePressed(evt);
            }
        });

        box4.setBackground(new java.awt.Color(255, 255, 255));
        box4.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        box4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box4.setOpaque(true);
        box4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box4MousePressed(evt);
            }
        });

        box5.setBackground(new java.awt.Color(255, 255, 255));
        box5.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        box5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box5.setOpaque(true);
        box5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box5MousePressed(evt);
            }
        });

        box6.setBackground(new java.awt.Color(255, 255, 255));
        box6.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        box6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box6.setOpaque(true);
        box6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box6MousePressed(evt);
            }
        });

        box7.setBackground(new java.awt.Color(255, 255, 255));
        box7.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        box7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box7.setToolTipText("");
        box7.setOpaque(true);
        box7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box7MousePressed(evt);
            }
        });

        box8.setBackground(new java.awt.Color(255, 255, 255));
        box8.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        box8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box8.setOpaque(true);
        box8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box8MousePressed(evt);
            }
        });

        box9.setBackground(new java.awt.Color(255, 255, 255));
        box9.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        box9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box9.setOpaque(true);
        box9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box9MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(box7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(box8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(box9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(box5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(111, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(118, 118, 118)
                    .addComponent(box5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(118, Short.MAX_VALUE)))
        );

        btnNextGame.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnNextGame.setText("Siguiente Juego");
        btnNextGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextGameActionPerformed(evt);
            }
        });

        btnInstructions.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnInstructions.setText("Instrucciones");
        btnInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructionsActionPerformed(evt);
            }
        });

        lblTurn.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        lblTurn.setText("Turno de X");

        lblScoreX.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblScoreX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreX.setText("X = ");

        lblPointsX.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblPointsX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPointsX.setText("0");

        lblScoreO.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblScoreO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreO.setText("O = ");

        lblPointsO.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblPointsO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPointsO.setText("0");

        lblWinner.setFont(new java.awt.Font("Dialog", 1, 39)); // NOI18N
        lblWinner.setText("El ganador es: X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWinner)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblScoreX)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblPointsX)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblScoreO)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblPointsO))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblTurn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnNextGame)))))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnInstructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTurn)
                    .addComponent(btnNextGame))
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScoreX)
                    .addComponent(lblScoreO)
                    .addComponent(lblPointsX)
                    .addComponent(lblPointsO))
                .addGap(18, 18, 18)
                .addComponent(lblWinner)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box1MousePressed

        press(1);
        
    }//GEN-LAST:event_box1MousePressed

    private void box2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box2MousePressed
        
        press(2);
        
    }//GEN-LAST:event_box2MousePressed

    private void box4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box4MousePressed
        
        press(4);
        
    }//GEN-LAST:event_box4MousePressed

    private void box3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box3MousePressed
        
        press(3);
        
    }//GEN-LAST:event_box3MousePressed

    private void box5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box5MousePressed
        
        press(5);
        
    }//GEN-LAST:event_box5MousePressed

    private void box6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box6MousePressed
        
        press(6);
        
    }//GEN-LAST:event_box6MousePressed

    private void box8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box8MousePressed
        
        press(8);
        
    }//GEN-LAST:event_box8MousePressed

    private void box7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box7MousePressed
        
        press(7);
        
    }//GEN-LAST:event_box7MousePressed

    private void box9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box9MousePressed
        
        press(9);
        
    }//GEN-LAST:event_box9MousePressed

    private void btnNextGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextGameActionPerformed
        
        if (Integer.parseInt(lblPointsX.getText()) != 3 && Integer.parseInt(lblPointsO.getText()) != 3) {
                
            for (int i = 0; i < boxes.length; i++) {

                boxes[i].setText("");
                boxes[i].setBackground(Color.WHITE);

            }

            turn = nextGame;

            if (nextGame == "O") {

                nextGame = "X";

            } else {

                nextGame = "O";

            }

            lblTurn.setText("Turno de " + turn);
            available = true;
        
        }
                        
    }//GEN-LAST:event_btnNextGameActionPerformed

    private void btnInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructionsActionPerformed
        
        String instructions =   "El objetivo consiste en vencer al oponente seleccionando la mejor estrategia, según las siguientes reglas:\n" +
                                "\n" +
                                "   * Cada jugador solo debe colocar su símbolo una vez por turno y no debe ser sobre una casilla ya jugada.\n" +
                                "   * Se debe conseguir realizar una línea horizontal, vertical o inclinada por símbolo.\n" +
                                "   * Se puede realizar movimientos horizontales, verticales y diagonales.\n" +
                                "\n" +
                                "En caso de empate (no se ha conseguido formar una línea horizontal, vertical o inclinada por símbolo), se juega otra vez.\n" +
                                "Esto se repite hasta que uno de los jugadores obtenga tres puntos, y será entonces el vencedor del juego.\n" +  
                                "\n";
        
        JOptionPane.showMessageDialog(null, instructions);
        
    }//GEN-LAST:event_btnInstructionsActionPerformed

    public void press(int cell) {
        
        if (boxes[cell - 1].getText() == "" && available == true) {
        
            boxes[cell - 1].setText(turn);
            changeTurn();
            if (checkGame() == false && tie() == true) {
            
                lblTurn.setText("Empate");
                
            }
            
        }
            
    }
    
    public void changeTurn() {
    
        if (turn == "X") {
        
                turn = "O";
        
        } else {
        
            turn = "X";
            
        }
        
        lblTurn.setText("Turno de " + turn);
    
    }
    
    public boolean checkGame() {
                               
        for (int i = 0; i < victories.length; i++) {

            if (boxes[victories[i][0] - 1].getText() == "X" && boxes[victories[i][1] - 1].getText() == "X" && boxes[victories[i][2] - 1].getText() == "X") {

                boxes[victories[i][0] - 1].setBackground(Color.GREEN);
                boxes[victories[i][1] - 1].setBackground(Color.GREEN);
                boxes[victories[i][2] - 1].setBackground(Color.GREEN);

                lblTurn.setText("Ha ganado X");
                lblPointsX.setText(Integer.toString(Integer.parseInt(lblPointsX.getText()) + 1));
                available = false;
                
                if (Integer.parseInt(lblPointsX.getText()) == 3) {
                
                    lblWinner.setVisible(true);
                    lblWinner.setText("El ganador es X");
                
                }
                
                return true;
                

            } else if (boxes[victories[i][0] - 1].getText() == "O" && boxes[victories[i][1] - 1].getText() == "O" && boxes[victories[i][2] - 1].getText() == "O") {

                boxes[victories[i][0] - 1].setBackground(Color.GREEN);
                boxes[victories[i][1] - 1].setBackground(Color.GREEN);
                boxes[victories[i][2] - 1].setBackground(Color.GREEN);

                lblTurn.setText("Ha ganado O");
                lblPointsO.setText(Integer.toString(Integer.parseInt(lblPointsO.getText()) + 1));
                available = false;
                
                if (Integer.parseInt(lblPointsO.getText()) == 3) {
                
                    lblWinner.setVisible(true);
                    lblWinner.setText("El ganador es O");
                
                }
                
                return true;

            }

        }
        
        return false;
            
    }
    
    public boolean tie() {
        
        for (int i = 0; i < boxes.length; i++) {
        
            if (boxes[i].getText() == "") {
            
                return false;
            
            }
        
        }
    
        return true;
    
    }
    
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel box1;
    private javax.swing.JLabel box2;
    private javax.swing.JLabel box3;
    private javax.swing.JLabel box4;
    private javax.swing.JLabel box5;
    private javax.swing.JLabel box6;
    private javax.swing.JLabel box7;
    private javax.swing.JLabel box8;
    private javax.swing.JLabel box9;
    private javax.swing.JButton btnInstructions;
    private javax.swing.JButton btnNextGame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPointsO;
    private javax.swing.JLabel lblPointsX;
    private javax.swing.JLabel lblScoreO;
    private javax.swing.JLabel lblScoreX;
    private javax.swing.JLabel lblTurn;
    private javax.swing.JLabel lblWinner;
    // End of variables declaration//GEN-END:variables
}
